services:

  backend:
    build: ./backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      API_URL: backend
      API_PORT: "3000"
    depends_on:
      - backend
